### ISSUE TITLE
Some suggestions.

### ISSUE THREAD

**Issue by tjbruce17594** [Sama34/OUGC-Custom-Reputation#25]
Hello! @Sama34 

I was wondering if these suggestions could be added for OUGC-Custom-Reputation.
1. Possibility to display the different ratings in tables in the user profile.

So like:

Likes:       Number received     Number Given
Dislikes     ""
Etc:           ""

Compatibility with the Flatty Theme?
1. Don't add to the reputation system, but add it to the plugin Thanks and Likes system?
   http://community.mybb.com/thread-169382.html

Thanks very much! :D

**Comment by Sama34** [comment]
Hi, for profile stats I will add them in 1.8.22, please see #12

For your second suggestion, about adding support for Thank you/Like System instead of the core reputation system I will consider tho I don't think it is a priority at the moment.
